name: Run Server Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Change to project directory
      run: cd spwai.github.io  # Adjust the directory name based on your project structure

    - name: Run Node.js server script
      run: node server.js
